pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/srujanbs12345/PES1UG22CS131__Jenkins-.git'
            }
        }

        stage('Build') 
            steps {
                sh 'g++ -o hello_exec main/hello.cpp'
            }
        }

        stage('Test') {
            steps {
                sh './hello_exec'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deployment stage (Placeholder for actual deployment)'
            }
        }
    }

    post {
        failure {
            echo 'Pipeline failed! Please check the logs.'
        }
        success {
            echo 'Pipeline executed successfully!'
        }
    }
}
